"use client"

import { useEffect, useMemo, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Server, Wifi, WifiOff, RefreshCw, Plus } from "lucide-react"
import type { Agent, ScanResult } from "@/lib/aetherscan/types"
import { fetchAgents, fetchScans, formatDateTime, registerAgent, timeAgo } from "@/lib/aetherscan-client"

export default function AgentsPage() {
  const [agents, setAgents] = useState<Agent[]>([])
  const [scans, setScans] = useState<ScanResult[]>([])
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [createdAgent, setCreatedAgent] = useState<(Agent & { authToken?: string }) | null>(null)
  const [form, setForm] = useState({ name: "", hostname: "", ipAddress: "", platform: "Kali Linux", description: "", mode: "live", targetHint: "" })

  const loadData = async () => {
    const [agentsData, scansData] = await Promise.all([fetchAgents(), fetchScans()])
    setAgents(agentsData)
    setScans(scansData)
  }

  useEffect(() => { void loadData() }, [])

  const onlineCount = agents.filter((agent) => agent.status === "online").length
  const offlineCount = agents.length - onlineCount
  const statsByAgent = useMemo(() => Object.fromEntries(agents.map((agent) => [agent.id, scans.filter((scan) => scan.agentId === agent.id)])), [agents, scans])

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">Scanning Agents</h1><p className="text-muted-foreground">Register agents, monitor status, and track real scan activity</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => loadData()}><RefreshCw className="mr-2 size-4" />Refresh</Button><Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}><DialogTrigger asChild><Button><Plus className="mr-2 size-4" />Add Agent</Button></DialogTrigger><DialogContent className="sm:max-w-[560px]"><DialogHeader><DialogTitle>Register Agent</DialogTitle><DialogDescription>Create a real agent record and use the generated token on the agent host</DialogDescription></DialogHeader><div className="grid gap-4 py-4"><div className="space-y-2"><Label>Name</Label><Input value={form.name} onChange={(event) => setForm((c) => ({ ...c, name: event.target.value }))} placeholder="e.g. Kali Scanner 01" /></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Hostname</Label><Input value={form.hostname} onChange={(event) => setForm((c) => ({ ...c, hostname: event.target.value }))} placeholder="kali-agent" /></div><div className="space-y-2"><Label>IP Address</Label><Input value={form.ipAddress} onChange={(event) => setForm((c) => ({ ...c, ipAddress: event.target.value }))} placeholder="192.168.1.60" /></div></div><div className="space-y-2"><Label>Platform</Label><Input value={form.platform} onChange={(event) => setForm((c) => ({ ...c, platform: event.target.value }))} /></div><div className="space-y-2"><Label>Description</Label><Input value={form.description} onChange={(event) => setForm((c) => ({ ...c, description: event.target.value }))} placeholder="Scanning host in the internal network" /></div><div className="space-y-2"><Label>Default Target Hint</Label><Input value={form.targetHint} onChange={(event) => setForm((c) => ({ ...c, targetHint: event.target.value }))} placeholder="e.g. 192.168.1.0/24" /></div>{createdAgent?.authToken ? <div className="rounded-lg border bg-muted/40 p-4 text-sm"><p className="font-medium mb-2">Agent token</p><code className="block break-all">{createdAgent.authToken}</code><p className="mt-3 font-medium mb-2">Run command on the agent host</p><code className="block whitespace-pre-wrap break-all">export AETHERSCAN_SERVER_URL="http://YOUR_SERVER_IP:3000"{`\n`}export AETHERSCAN_AGENT_TOKEN=""{`\n`}export AETHERSCAN_ONCE=false{`\n`}node ./scripts/aetherscan-agent.mjs</code></div> : null}</div><DialogFooter><Button variant="outline" onClick={() => setIsDialogOpen(false)}>Close</Button><Button onClick={async () => { const agent = await registerAgent(form); setCreatedAgent(agent); await loadData() }}>Register Agent</Button></DialogFooter></DialogContent></Dialog></div></div>
      <div className="grid gap-4 sm:grid-cols-4"><Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Total Agents</CardTitle><Server className="size-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{agents.length}</div><p className="text-xs text-muted-foreground">Registered agents</p></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Online</CardTitle><Wifi className="size-4 text-green-600" /></CardHeader><CardContent><div className="text-2xl font-bold text-green-600">{onlineCount}</div><p className="text-xs text-muted-foreground">Actively reporting</p></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Offline</CardTitle><WifiOff className="size-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{offlineCount}</div><p className="text-xs text-muted-foreground">No recent heartbeat</p></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">Total Scans</CardTitle><RefreshCw className="size-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-2xl font-bold">{scans.length}</div><p className="text-xs text-muted-foreground">Completed or queued jobs</p></CardContent></Card></div>
      <div className="grid gap-4 md:grid-cols-2">{agents.length ? agents.map((agent) => { const agentScans = statsByAgent[agent.id] ?? []; const lastScan = agentScans[0]; return <Card key={agent.id}><CardHeader className="pb-2"><div className="flex items-start gap-3"><div className={`rounded-md p-2 ${agent.status === "online" ? "bg-green-100 text-green-600" : "bg-muted text-muted-foreground"}`}><Server className="size-5" /></div><div><CardTitle className="text-base">{agent.name}</CardTitle><CardDescription>{agent.platform} • {agent.hostname}</CardDescription></div></div></CardHeader><CardContent><div className="space-y-3"><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">Status</span><Badge variant={agent.status === "online" ? "secondary" : "outline"} className={agent.status === "online" ? "bg-green-100 text-green-700 border-green-200" : ""}>{agent.status}</Badge></div><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">IP Address</span><code className="bg-muted px-2 py-0.5 rounded text-xs">{agent.ipAddress}</code></div><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">Last Seen</span><span>{timeAgo(agent.lastSeenAt)}</span></div><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">Queued/Completed Scans</span><span className="font-medium">{agentScans.length}</span></div><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">Last Scan</span><span className="text-muted-foreground">{lastScan ? formatDateTime(lastScan.completedAt ?? lastScan.startedAt) : "Never"}</span></div><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">Target Hint</span><span className="text-muted-foreground">{agent.targetHint || "Not set"}</span></div></div></CardContent></Card> }) : <Card className="md:col-span-2"><CardContent className="p-8 text-center text-sm text-muted-foreground">No agents registered yet. Register an agent, then start the agent process on the target host.</CardContent></Card>}</div>
    </div>
  )
}

